name: Package Application with Pyinstaller
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with: 
            python-version: "3.10"
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Show ctk path
        run: |
          pip show customtkinter
      
      #Path should be fetched dynamically if possible...
      - name: Run PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --windowed --add-data "c:\hostedtoolcache\windows\python\3.10.11\x64\lib\site-packages\customtkinter;customtkinter\" main.py;
      
      - uses: actions/upload-artifact@v3
        with:
            name: windows-executeable
            path: dist/main
#      - uses: actions/upload-artifact@v2
#        with:
#          name: Windows_qwiklabs
#          path: dist/main
