name: Create Ubuntu Executeable
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with: 
            python-version: "3.10"
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Show ctk path
        run: |
          pip show customtkinter
          pip show Pillow
      
      #Path should be fetched dynamically if possible...
      - name: Run PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --windowed --add-data "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/customtkinter:customtkinter/" --add-data "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/PIL:PIL/" main.py;

      - uses: actions/upload-artifact@v3
        with:
            name: ubuntu-executeable
            path: dist/main/
